group: aafc
objectstore-api:
  metadata:
    attributes:
      acSubtype: "OBJECT SUBTYPE 1"
      dcType: "IMAGE"
      managedAttributes: { legacy_barcode: "123" }
      orientation: 1
      xmpRightsOwner: "Government of Canada"
      xmpRightsUsageTerms: ""
      xmpRightsWebStatement: ""
      dcRights: "© His Majesty The King in Right of Canada, as represented by the Minister of Agriculture and Agri-Food | © Sa Majesté le Roi du chef du Canada, représentée par le ministre de l’Agriculture et de l’Agroalimentaire"
    relationships:
      dcCreator: "afcf0bcc-c6c8-40c5-b97b-1855ce5d1729"
