name: dina-py CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install package with dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -e .[test]

      - name: Run all tests
        run: |
          pytest tests/ -v

  # --- Test  for merges on a branch - Will change to main once confirmed---
  publish:
    name: Publish to TestPyPI
    needs: build
    if: |
      github.event_name == 'push' &&
      (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/Support-38221-PyPi_packaging')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build
        
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # This line redirects the upload from the real PyPI to TestPyPI
          repository-url: https://test.pypi.org/legacy/